// Basic Game 
// Generate AI HTML, CSS and JS code for Rock Paper Scissors game 🍏 
// Paste into the correct files 🍏 
// Does the game work? 🍏 
    // - HTML and CSS linked to show a themed static page, JS functions 🍏 

// This is the code generated by ChatGPT in response to request - 
// please may I have the javascript for the HTML above?

const rock = document.getElementById("rock");
const paper = document.getElementById("paper");
const scissors = document.getElementById("scissors");

const playerChoiceText = document.getElementById("player-choice-text");
const computerChoiceText = document.getElementById("computer-choice-text");
const outcomeText = document.getElementById("outcome-text");

const playerScoreText = document.getElementById("player-score-text");
const computerScoreText = document.getElementById("computer-score-text");

let playerScore = 0;
let computerScore = 0;

function computerPlay() {
    const choices = ["Rock", "Paper", "Scissors"];
    return choices[Math.floor(Math.random() * choices.length)];
}

function playRound(playerSelection, computerSelection) {
    if (playerSelection === computerSelection) {
        return "Draw";
    } else if (
        (playerSelection === "Rock" && computerSelection === "Scissors") ||
        (playerSelection === "Paper" && computerSelection === "Rock") ||
        (playerSelection === "Scissors" && computerSelection === "Paper")
    ) {
        return "Player";
    } else {
        return "Computer";
    }
}

function updateScoreboard() {
    playerScoreText.textContent = playerScore;
    computerScoreText.textContent = computerScore;
}

function handleClick(choice) {
    const computerChoice = computerPlay();
    const result = playRound(choice, computerChoice);

    playerChoiceText.textContent = choice;
    computerChoiceText.textContent = computerChoice;

    if (result === "Draw") {
        outcomeText.textContent = "It's a draw!";
    } else if (result === "Player") {
        outcomeText.textContent = "You win!";
        playerScore++;
    } else {
        outcomeText.textContent = "Computer wins!";
        computerScore++;
    }

    updateScoreboard();
}

rock.addEventListener("click", () => handleClick("Rock"));
paper.addEventListener("click", () => handleClick("Paper"));
scissors.addEventListener("click", () => handleClick("Scissors"));





